# Generated by Django 3.0.2 on 2020-01-29 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 9, 34, 44, 77856, tzinfo=utc)),
        ),
    ]
